- hosts: all
  become: yes
  vars:
    jenkins_port: 9090

  tasks:
    - name: Stop Jenkins service
      systemd:
        name: jenkins
        state: stopped
      notify: Restart Jenkins

    - name: Ensure Jenkins process is not running
      command: pkill -f jenkins || true
      ignore_errors: yes

    - name: Update Jenkins port in /etc/default/jenkins
      template:
        src: jenkins.j2
        dest: /etc/default/jenkins
      notify: Restart Jenkins

    - name: Modify Jenkins systemd service file
      template:
        src: jenkins.service.j2
        dest: /lib/systemd/system/jenkins.service
      notify: Reload systemd daemon

  handlers:
    - name: Reload systemd daemon
      command: systemctl daemon-reload
      notify: Restart Jenkins

    - name: Restart Jenkins
      systemd:
        name: jenkins
        state: restarted
