  hosts: all
  become: yes
  tasks:
    - name: Stop Jenkins service
      systemd:
        name: jenkins
        state: stopped
      notify: Restart Jenkins

    - name: Ensure Jenkins process is not running
      command: pkill -f jenkins || true
      ignore_errors: yes

    - name: Update Jenkins port in /etc/default/jenkins
      lineinfile:
        path: /etc/default/jenkins
        regexp: '^HTTP_PORT='
        line: 'HTTP_PORT=9090'
      notify: Restart Jenkins

    - name: Modify Jenkins systemd service file
      lineinfile:
        path: /lib/systemd/system/jenkins.service
        regexp: '^ExecStart='
        line: 'ExecStart=/usr/bin/java -Djava.awt.headless=true -jar /usr/share/java/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=9090'
      notify: Reload systemd daemon

  handlers:
    - name: Reload systemd daemon
      command: systemctl daemon-reload
      notify: Restart Jenkins

    - name: Restart Jenkins
      systemd:
        name: jenkins
        state: restarted



