- hosts: all
  become: yes
  tasks:
    - name: Retrieve Jenkins password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password

    - name: Display Jenkins password
      debug:
        msg: "Jenkins initial password is {{ jenkins_password.stdout }}"
