- hosts: all
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: ["openjdk-11-jdk", "wget"]
        state: present

    - name: Add Jenkins repository
      shell: |
        wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
        sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start and Enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: yes